# Site settings
title: Jess Young
email: jess@soijen.com
description: Jess Young
lang: ["en", "es"]
url: "https://jessyoung.ninja"
author: Jess Young
twitter_username: J_joven_
permalink: /:title/
google_maps_api_key:

# Build settings
include: ["_pages"]

defaults:
  #languages
  -
    scope:
      path: "en"
    values:
      lang: "en"
      baseurl: ""
  -
    scope:
      path: "es"
    values:
      lang: "es"
      baseurl: "/es/"

#menu translations
t:
  en:
    home:
      name: "Home"
      url: "/"
    about:
      name: "CV"
      url: "/about/"
    portfolio:
      name: "Portfolio"
      url: "/portfolio/"
    blog:
      name: "Blog"
      url: "/blog/"
    running:
      name: "Running"
      url: "/running/"
    contact:
      name: "Contact"
      url: "/#contact"
  es:
      home:
        name: "Inicio"
        url: "/es/"
      about:
        name: "CV"
        url: "/es/about/"
      portfolio:
        name: "Portafolio"
        url: "/es/portfolio/"
      blog:
        name: "Blog"
        url: "/es/blog/"
      running:
        name: "Correr"
        url: "/es/running/"
      contact:
        name: "Contacto"
        url: "/es/#contact"
