# Site settings
title: Jess Young
email: jess@soijen.com
description:
  en: Systems ninja + trail runner
  es: Operaciones ninja + corredor de montañas
index:
  en:
  es: /es/index.html
feed:
  en: /feed.xml
  es: /es/feed.xml
lang: ["en", "es"]
url: "https://jessyoung.info"
author: Jess Young
twitter_username: _jjoven_
facebook_username: jessica.young.5492
instagram_username: _jjoven_
linkedin_username: jessmyoung
permalink: /:title/

# Build settings
include: ["_pages"]

collections:
  portfolio:
    output: false

defaults:
  #languages
  -
    scope:
      path: "en"
    values:
      lang: "en"
      baseurl: ""
  -
    scope:
      path: "es"
    values:
      lang: "es"
      baseurl: "/es/"

#menu translations
t:
  en:
    home:
      name: "Home"
      url: "/"
    about:
      name: "CV"
      url: "/about/"
    portfolio:
      name: "Portfolio"
      url: "/portfolio/"
    running:
      name: "Running"
      url: "/running/"
    contact:
      name: "Contact"
      url: "/#contact"
  es:
      home:
        name: "Inicio"
        url: "/es/"
      about:
        name: "CV"
        url: "/es/about/"
      portfolio:
        name: "Portafolio"
        url: "/es/portfolio/"
      running:
        name: "Correr"
        url: "/es/running/"
      contact:
        name: "Contacto"
        url: "/es/#contact"
