# Site settings
title: Jess Young
email: jess@soijen.com
description: Jess Young's personal website
lang: ["en", "es"]
url: "http://jessyoung.ninja"
author: jjoven
permalink: /:title/
google_maps_api_key:

# Build settings
include: ["_pages"]

defaults:
  #languages
  -
    scope:
      path: "en"
    values:
      lang: "en"
      baseurl: ""
  -
    scope:
      path: "es"
    values:
      lang: "es"
      baseurl: "/es/"

#menu translations
t:
  en:
    home:
      name: "Home"
      url: "/"
    about:
      name: "CV"
      url: "/about/"
    projects:
      name: "Projects"
      url: "/projects/"
    running:
      name: "Running"
      url: "/running/"
    contact:
      name: "Contact"
      url: "/#contact"
  es:
      home:
        name: "Inicio"
        url: "/es/"
      about:
        name: "CV"
        url: "/es/about/"
      projects:
        name: "Proyectos"
        url: "/es/projects/"
      running:
        name: "Correr"
        url: "/es/running/"
      contact:
        name: "Contacto"
        url: "/#contact"
